### ISSUE TITLE
Cannot load gem in version 1.1.0

### ISSUE THREAD

**Issue by franzliedke** [julik/idempo#19]
When using the gem with version 1.1.0 (just got a Dependabot PR), `require "idempo"` fails with:

```
/drone/src/vendor/bundle/ruby/3.3.0/gems/idempo-1.1.0/lib/idempo/active_record_backend.rb:2:in `<main>': uninitialized constant Idempo (NameError)

class Idempo::ActiveRecordBackend
```

That's because the order of the `require` statements [was changed](https://github.com/julik/idempo/compare/v1.0.0...v1.1.0#diff-ce016a0b5437b51797bc426f223565b2e784c435fa82cd7a5f2eee618f1c5289) - I guess `require "idempo/version"` should still come first.

Was this a standardrb thing? In this case, the alternative would be to nest the modules instead of defining classes with the shortcut `class Idempo::ActiveRecordBackend` syntax. Happy to send a PR if you tell me which version you prefer. 😉

**Comment by julik** [comment]
Good catch! Yes, please do send a PR. What do you mean by "which version"? what should we bump the gem version to? If that, I will take care of it and it will likely be a patch version bump 🙏

**Comment by julik** [comment]
Actually - come to think of it, maybe we should use `autoload` for the various backends? This would allow people not to load code they never use.

**Comment by franzliedke** [comment]
> Happy to send a PR if you tell me which version you prefer. 

I was asking which of the two alternatives I should implement. But you already fixed it, great!

Thanks! And also for inviting me to the repo. 🤗
