### ISSUE TITLE
Question: Risks of omitting the body in the fingerprint?

### ISSUE THREAD

**Issue by franzliedke** [julik/idempo#21]
I hope it's okay to use an issue for a question like this...

---

Hypothesis: In theory, the idempotency key (combined with the path) should suffice to make a POST request unique.

Of course, this depends on how the client generates this key. In our case, the client is submitting offline-generated resources to the server. These resources have local UUIDs, which we use as key.

In our analysis, we discovered that it could be possible for the client to make further changes to an offline-only resource after a first unsuccessful request, which would mean the body would look different when retrying, i.e. sending a second request. If the request body is part of the fingerprint, this would no longer be de-duplicated, potentially resulting in a duplicate on the server (because the first request actually succeeded, but the client did not receive the response).

We now excluded this case: edits to resources are only possible a) before the first request and b) once we know for sure that the server has received the data.

The reason why we'd like to omit the request body from the fingerprint: It means the client has to jump through fewer hoops to ensure that the request bodies are serialized deterministically (ordering of keys in JSON objects, as well as objects in unordered lists). So we're trying to decide between two constraints the client has to fulfill:
- deterministic request body serialization
- preventing edits to resources between first request and first successful response

Because the second option also means less storage needs and complexity on the server (okay, it's encapsulated in the gem), we're leaning towards omitting the request body from the fingerprint.

Do you see any danger with that? Am I missing any other important aspect for why it's needed?

**Comment by julik** [comment]
Of course it is fine to discuss things like this, no worries.

The reason why the fingerprint is injectable in the configuration is exactly for things like these. For example, you might want to honor only the idempotency key and nothing else. Or you might want to honor the idempotency key + the authentication. That decision is up to you.

The obvious use case with idempo is of course protecting from retries with the same request body. But you are absolutely free to make a different choice there.

If your concern is deterministic request body serialization, you can parse the request body inside the fingerprint handling proc, re-serialize it in a "canonical" format that you know is correct (lexicographically sorted keys, for example), and calculate the fingerprint off of that.

I don't really see any risks as such. The only risk I am aware of is that multiple clients (or: multiple users/principals) use the same idempotency keys and may access each other's responses. This is why the fingerprint code includes the authorization header. But again: this might very well not be a concern for you, so all doors are open there.

**Comment by franzliedke** [comment]
Cool, thank you very much for your response! 💚 

> If your concern is deterministic request body serialization, you can parse the request body inside the fingerprint handling proc, re-serialize it in a "canonical" format that you know is correct (lexicographically sorted keys, for example), and calculate the fingerprint off of that.

True, that would also be a good solution with less complexity on the client side.

As I see no downside given our context (UUID keys, plus we still include the authorization header), I'll go for simplicity and will completely omit the request body (even a canonical one).

Thanks again!
